name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies with legacy-peer-deps
        run: npm install --legacy-peer-deps

      - name: Run tests (if any)
        run: npm test || echo "No tests defined"

      - name: Build (if applicable)
        run: npm run build || echo "No build step"
